### Sign Up User
POST http://localhost:5000/api/auth/signup HTTP/1.1
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "145678",
    "username": "tes",
    "fullname": " lklkj"
}

###
POST http://localhost:5000/api/posts HTTP/1.1
Content-Type: application/json

{
    "id" : 34234,
    "description" : "Hi from Salman"
}

### Sign In User
POST http://localhost:5000/api/auth/signin HTTP/1.1
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "145678"
}


### Sign Out
POST http://localhost:5000/api/auth/signout HTTP/1.1
Content-Type: application/json


### Fetch posts
GET http://localhost:5000/api/