### Sign Up User
POST http://localhost:5000/api/auth/signup HTTP/1.1
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "145678",
    "username": "tes",
    "fullname": " lklkj"
}

###
POST http://localhost:5000/api/posts HTTP/1.1
Content-Type: application/json

{
    "id" : 34234,
    "description" : "The virus that causes COVID-19 is mainly transmitted through droplets generated when an infected person coughs, sneezes, or exhales. These droplets are too heavy to hang in the air, and quickly fall on floors or surfaces.",
    "user_id": 6
}

### Sign In User
POST http://localhost:5000/api/auth/signin HTTP/1.1
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "145678"
}


### Sign Out
POST http://localhost:5000/api/auth/signout HTTP/1.1
Content-Type: application/json


###
GET http://localhost:5000/api/auth/current HTTP/1.1
Content-Type: application/json

###
DELETE  http://localhost:5000/api/posts/34234 HTTP/1.1
Content-Type: application/json